# Generated by Django 5.2.7 on 2025-10-30 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_session_ended_at_session_provider_room_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("subject", models.CharField(blank=True, max_length=100, null=True)),
                ("system_prompt", models.TextField(blank=True, null=True)),
                ("student_goal", models.TextField(blank=True, null=True)),
                ("message_count", models.PositiveIntegerField(default=0)),
                ("duration_minutes", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_message_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_conversations",
                        to="courses.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"role": "STUDENT"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="AIMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("user", "User"),
                            ("assistant", "Assistant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("has_audio", models.BooleanField(default=False)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="ai_audio/"),
                ),
                (
                    "audio_duration_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("model_used", models.CharField(blank=True, max_length=50, null=True)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("response_time_ms", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="courses.aiconversation",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "Poor"),
                            (2, "Fair"),
                            (3, "Good"),
                            (4, "Very Good"),
                            (5, "Excellent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("is_helpful", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="courses.aimessage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["student", "is_active"], name="courses_aic_student_7d9a0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["course", "started_at"], name="courses_aic_course__394ce1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimessage",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="courses_aim_convers_c8b288_idx",
            ),
        ),
    ]
